services:
  pwa-engine:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: pwa-engine
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: air
